
# Cloudflare Workers の設定
# ref: https://developers.cloudflare.com/workers/wrangler/configuration/

# Worker スクリプトの名前
name = 'konomitv-api'

# Worker としてアップロードされる JavaScript ファイルのパス
main = 'dist/worker.mjs'

# Worker の動作に互換性を持たせる日付
## この日付より前に行われた Cloudflare Workers の変更がすべて有効化される
## この日付より後に行われた Cloudflare Workers の変更は日付を更新しない限り有効化されない
## ref: https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = '2022-11-30'

# Worker を *.workers.dev にデプロイするかどうかを指定するフラグ
workers_dev = false

# Worker を実行する Zone 上の、URLパターンで指定されたルート
# アスタリスク (*) で複数の URL に一致する動的パターンを作成できる
route = 'app.konomi.tv/api/*'

# ビルドコマンド
[build]
command = 'yarn build'
